# System 2 Disconnected Configuration
# Deliberate decision-making without social connectivity

log_levels:
  agent: 0
  link: 0
  camp: 0
  conflict: 0
  init: 0
  granularity: location

spawn_rules:
  take_from_population: false
  insert_day0: true

move_rules:
  max_move_speed: 360.0
  max_walk_speed: 35.0
  foreign_weight: 1.0
  camp_weight: 1.0
  conflict_weight: 0.25
  conflict_movechance: 1.0
  camp_movechance: 0.001
  default_movechance: 0.3
  awareness_level: 3
  capacity_scaling: 1.0
  avoid_short_stints: false
  start_on_foot: false
  weight_power: 1.0
  two_system_decision_making: true
  average_social_connectivity: 0.0
  weight_softening: 0.1
  conflict_threshold: 0.5
  recovery_period_max: 14

optimisations:
  hasten: 1