log_levels:
  agent: 1
  camp: 0
  init: 0
  Flood: 0
  link: 0

# Set to 100 to scale down the population by 100 and increase the execution time.
optimisations:
  hasten: 1

spawn_rules:
  take_from_population: False
  Flood_spawn_decay: [1.0,1.0,1.0,0.5,0.1]